import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  monkSidebar: [
    '11.1-FAQ',
    'playstyle',
    'chiji',
    'herotalents',
    'talents',
    {
      type: 'category',
      label: 'Master of Harmony',
      items: [
        'master-of-harmony/about',
        'master-of-harmony/aspect-of-harmony',
        'master-of-harmony/healing-damage',
        'master-of-harmony/coalescence',
        'master-of-harmony/playstyle',
        'master-of-harmony/cheat-sheet',
        'master-of-harmony/tips-and-tricks',
        'master-of-harmony/faq'
      ],
      collapsed: true,
    },
  ]
};

export default sidebars;
